services:
  - type: web
    name: fin-backend
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn unified_backend:app
    rootDir: backend
    envVars:
      - key: NEWS_API_KEY
        description: "API Key for NewsAPI"
      - key: PYTHON_VERSION
        value: 3.9.0
